use Names
GO

insert into [dbo].[SeedTable]  ([LastNames],[FirstNames],[streetnames],[city],[state],[gender]) values ('Johnson','Jacob','Mt Princeton Dr','Leadville','CO','m')
insert into [dbo].[SeedTable]  ([LastNames],[FirstNames],[streetnames],[city],[state],[gender]) values ('Williams','Mason','Mt Massive Dr','Leadville','CO','m')
insert into [dbo].[SeedTable]  ([LastNames],[FirstNames],[streetnames],[city],[state],[gender]) values ('Brown','William','Mt Elber Dr','Leadville','CO','m')
insert into [dbo].[SeedTable]  ([LastNames],[FirstNames],[streetnames],[city],[state],[gender]) values ('Jones','Jayden','County Road 17','Leadville','CO','m')
insert into [dbo].[SeedTable]  ([LastNames],[FirstNames],[streetnames],[city],[state],[gender]) values ('Miller','Noah','County Road 9','Leadville','CO','m')
insert into [dbo].[SeedTable]  ([LastNames],[FirstNames],[streetnames],[city],[state],[gender]) values ('Davis','Michael','County Road 37','Leadville','CO','m')
insert into [dbo].[SeedTable]  ([LastNames],[FirstNames],[streetnames],[city],[state],[gender]) values ('García','Ethan','County Road 99','Leadville','CO','m')
insert into [dbo].[SeedTable]  ([LastNames],[FirstNames],[streetnames],[city],[state],[gender]) values ('Rodríguez','Alexander','Highway 24','Leadville','CO','m')
insert into [dbo].[SeedTable]  ([LastNames],[FirstNames],[streetnames],[city],[state],[gender]) values ('Wilson','Aiden','Mt Yale Dr','Leadville','CO','m')
insert into [dbo].[SeedTable]  ([LastNames],[FirstNames],[streetnames],[city],[state],[gender]) values ('Martínez','Daniel','Mt Columbus Dr','Leadville','CO','m')
insert into [dbo].[SeedTable]  ([LastNames],[FirstNames],[streetnames],[city],[state],[gender]) values ('Anderson','Anthony','Mt Harvard Dr','Leadville','CO','m')
insert into [dbo].[SeedTable]  ([LastNames],[FirstNames],[streetnames],[city],[state],[gender]) values ('Taylor','Matthew','Mt Oxfort Dr','Leadville','CO','m')
insert into [dbo].[SeedTable]  ([LastNames],[FirstNames],[streetnames],[city],[state],[gender]) values ('Thomas','Elijah','Mt Lincoln Dr','Leadville','CO','m')
insert into [dbo].[SeedTable]  ([LastNames],[FirstNames],[streetnames],[city],[state],[gender]) values ('Hernández','Joshua','James St','Leadville','CO','m')
insert into [dbo].[SeedTable]  ([LastNames],[FirstNames],[streetnames],[city],[state],[gender]) values ('Moore','Liam','6th St','Leadville','CO','m')
insert into [dbo].[SeedTable]  ([LastNames],[FirstNames],[streetnames],[city],[state],[gender]) values ('Martin','Andrew','7th St','Leadville','CO','m')
insert into [dbo].[SeedTable]  ([LastNames],[FirstNames],[streetnames],[city],[state],[gender]) values ('Jackson','James','8th St','Leadville','CO','m')
insert into [dbo].[SeedTable]  ([LastNames],[FirstNames],[streetnames],[city],[state],[gender]) values ('Thompson','David','9th St','Leadville','CO','m')
insert into [dbo].[SeedTable]  ([LastNames],[FirstNames],[streetnames],[city],[state],[gender]) values ('White','Benjamin','10th St','Leadville','CO','m')
insert into [dbo].[SeedTable]  ([LastNames],[FirstNames],[streetnames],[city],[state],[gender]) values ('López','Logan','11 St','Leadville','CO','m')
insert into [dbo].[SeedTable]  ([LastNames],[FirstNames],[streetnames],[city],[state],[gender]) values ('Lee','Christopher','12 St','Leadville','CO','m')
insert into [dbo].[SeedTable]  ([LastNames],[FirstNames],[streetnames],[city],[state],[gender]) values ('González','Joseph','Poplar St','Leadville','CO','m')
insert into [dbo].[SeedTable]  ([LastNames],[FirstNames],[streetnames],[city],[state],[gender]) values ('Harris','Jackson','Spruce St','Leadville','CO','m')
insert into [dbo].[SeedTable]  ([LastNames],[FirstNames],[streetnames],[city],[state],[gender]) values ('Clark','Gabriel','Elm St','Leadville','CO','m')
insert into [dbo].[SeedTable]  ([LastNames],[FirstNames],[streetnames],[city],[state],[gender]) values ('Lewis','Ryan','Loomis St','Leadville','CO','m')
insert into [dbo].[SeedTable]  ([LastNames],[FirstNames],[streetnames],[city],[state],[gender]) values ('Robinson','Samuel','Maple St','Leadville','CO','m')
insert into [dbo].[SeedTable]  ([LastNames],[FirstNames],[streetnames],[city],[state],[gender]) values ('Walker','John','Hazel St','Leadville','CO','m')
insert into [dbo].[SeedTable]  ([LastNames],[FirstNames],[streetnames],[city],[state],[gender]) values ('Pérez','Nathan','Alder St','Leadville','CO','m')
insert into [dbo].[SeedTable]  ([LastNames],[FirstNames],[streetnames],[city],[state],[gender]) values ('Hall','Lucas','Pine St','Leadville','CO','m')
insert into [dbo].[SeedTable]  ([LastNames],[FirstNames],[streetnames],[city],[state],[gender]) values ('Young','Christian','','Leadville','CO','m')
insert into [dbo].[SeedTable]  ([LastNames],[FirstNames],[streetnames],[city],[state],[gender]) values ('Allen','Jonathan','','Leadville','CO','m')
insert into [dbo].[SeedTable]  ([LastNames],[FirstNames],[streetnames],[city],[state],[gender]) values ('Sánchez','Caleb','','Leadville','CO','m')
insert into [dbo].[SeedTable]  ([LastNames],[FirstNames],[streetnames],[city],[state],[gender]) values ('Wright','Dylan','','Leadville','CO','m')
insert into [dbo].[SeedTable]  ([LastNames],[FirstNames],[streetnames],[city],[state],[gender]) values ('King','Landon','','Leadville','CO','m')
insert into [dbo].[SeedTable]  ([LastNames],[FirstNames],[streetnames],[city],[state],[gender]) values ('Scott','Isaac','','Leadville','CO','m')
insert into [dbo].[SeedTable]  ([LastNames],[FirstNames],[streetnames],[city],[state],[gender]) values ('Green','Gavin','','Leadville','CO','m')
insert into [dbo].[SeedTable]  ([LastNames],[FirstNames],[streetnames],[city],[state],[gender]) values ('Baker','Brayden','','Leadville','CO','m')
insert into [dbo].[SeedTable]  ([LastNames],[FirstNames],[streetnames],[city],[state],[gender]) values ('Adams','Tyler','','Leadville','CO','m')
insert into [dbo].[SeedTable]  ([LastNames],[FirstNames],[streetnames],[city],[state],[gender]) values ('Nelson','Luke','','Leadville','CO','m')
insert into [dbo].[SeedTable]  ([LastNames],[FirstNames],[streetnames],[city],[state],[gender]) values ('Hill','Evan','','Leadville','CO','m')
insert into [dbo].[SeedTable]  ([LastNames],[FirstNames],[streetnames],[city],[state],[gender]) values ('Ramírez','Carter','','Leadville','CO','m')
insert into [dbo].[SeedTable]  ([LastNames],[FirstNames],[streetnames],[city],[state],[gender]) values ('Campbell','Nicholas','','Leadville','CO','m')
insert into [dbo].[SeedTable]  ([LastNames],[FirstNames],[streetnames],[city],[state],[gender]) values ('Mitchell','Isaiah','','Leadville','CO','m')
insert into [dbo].[SeedTable]  ([LastNames],[FirstNames],[streetnames],[city],[state],[gender]) values ('Roberts','Owen','','Leadville','CO','m')
insert into [dbo].[SeedTable]  ([LastNames],[FirstNames],[streetnames],[city],[state],[gender]) values ('Carter','Jack','','Leadville','CO','m')
insert into [dbo].[SeedTable]  ([LastNames],[FirstNames],[streetnames],[city],[state],[gender]) values ('Phillips','Jordan','','Leadville','CO','m')
insert into [dbo].[SeedTable]  ([LastNames],[FirstNames],[streetnames],[city],[state],[gender]) values ('Evans','Brandon','','Leadville','CO','m')
insert into [dbo].[SeedTable]  ([LastNames],[FirstNames],[streetnames],[city],[state],[gender]) values ('Turner','Wyatt','','Leadville','CO','m')
insert into [dbo].[SeedTable]  ([LastNames],[FirstNames],[streetnames],[city],[state],[gender]) values ('Torres','Julian','','Leadville','CO','m')
insert into [dbo].[SeedTable]  ([LastNames],[FirstNames],[streetnames],[city],[state],[gender]) values ('Parker','Arianna','','Leadville','CO','f')
insert into [dbo].[SeedTable]  ([LastNames],[FirstNames],[streetnames],[city],[state],[gender]) values ('Collins','Peyton','','Leadville','CO','f')
insert into [dbo].[SeedTable]  ([LastNames],[FirstNames],[streetnames],[city],[state],[gender]) values ('Edwards','Harper','','Leadville','CO','f')
insert into [dbo].[SeedTable]  ([LastNames],[FirstNames],[streetnames],[city],[state],[gender]) values ('Stewart','Alexa','','Leadville','CO','f')
insert into [dbo].[SeedTable]  ([LastNames],[FirstNames],[streetnames],[city],[state],[gender]) values ('Flores','Makayla','','Leadville','CO','f')
insert into [dbo].[SeedTable]  ([LastNames],[FirstNames],[streetnames],[city],[state],[gender]) values ('Morris','Julia','','Leadville','CO','f')
insert into [dbo].[SeedTable]  ([LastNames],[FirstNames],[streetnames],[city],[state],[gender]) values ('Nguyen','Kylie','','Leadville','CO','f')
insert into [dbo].[SeedTable]  ([LastNames],[FirstNames],[streetnames],[city],[state],[gender]) values ('Murphy','Kayla','','Leadville','CO','f')
insert into [dbo].[SeedTable]  ([LastNames],[FirstNames],[streetnames],[city],[state],[gender]) values ('Rivera','Bella','','Leadville','CO','f')
insert into [dbo].[SeedTable]  ([LastNames],[FirstNames],[streetnames],[city],[state],[gender]) values ('Cook','Katherine','','Leadville','CO','f')
insert into [dbo].[SeedTable]  ([LastNames],[FirstNames],[streetnames],[city],[state],[gender]) values ('Rogers','Lauren','','Leadville','CO','f')
insert into [dbo].[SeedTable]  ([LastNames],[FirstNames],[streetnames],[city],[state],[gender]) values ('Morgan','Gianna','','Leadville','CO','f')
insert into [dbo].[SeedTable]  ([LastNames],[FirstNames],[streetnames],[city],[state],[gender]) values ('Peterson','Maya','','Leadville','CO','f')
insert into [dbo].[SeedTable]  ([LastNames],[FirstNames],[streetnames],[city],[state],[gender]) values ('Cooper','Sydney','','Leadville','CO','f')
insert into [dbo].[SeedTable]  ([LastNames],[FirstNames],[streetnames],[city],[state],[gender]) values ('Reed','Serenity','','Leadville','CO','f')
insert into [dbo].[SeedTable]  ([LastNames],[FirstNames],[streetnames],[city],[state],[gender]) values ('Bailey','Kimberly','','Leadville','CO','f')
insert into [dbo].[SeedTable]  ([LastNames],[FirstNames],[streetnames],[city],[state],[gender]) values ('Bell','Mackenzie','','Leadville','CO','f')
insert into [dbo].[SeedTable]  ([LastNames],[FirstNames],[streetnames],[city],[state],[gender]) values ('Gómez','Autumn','','Leadville','CO','f')
insert into [dbo].[SeedTable]  ([LastNames],[FirstNames],[streetnames],[city],[state],[gender]) values ('Kelly','Jocelyn','','Leadville','CO','f')
insert into [dbo].[SeedTable]  ([LastNames],[FirstNames],[streetnames],[city],[state],[gender]) values ('Howard','Faith','','Leadville','CO','f')
insert into [dbo].[SeedTable]  ([LastNames],[FirstNames],[streetnames],[city],[state],[gender]) values ('Ward','Lucy','','Leadville','CO','f')
insert into [dbo].[SeedTable]  ([LastNames],[FirstNames],[streetnames],[city],[state],[gender]) values ('Cox','Stella','','Leadville','CO','f')
insert into [dbo].[SeedTable]  ([LastNames],[FirstNames],[streetnames],[city],[state],[gender]) values ('Díaz','Jasmine','','Leadville','CO','f')
insert into [dbo].[SeedTable]  ([LastNames],[FirstNames],[streetnames],[city],[state],[gender]) values ('Richardson','Morgan','','Leadville','CO','f')
insert into [dbo].[SeedTable]  ([LastNames],[FirstNames],[streetnames],[city],[state],[gender]) values ('Wood','Alexandra','','Leadville','CO','f')
insert into [dbo].[SeedTable]  ([LastNames],[FirstNames],[streetnames],[city],[state],[gender]) values ('Watson','Trinity','','Leadville','CO','f')
insert into [dbo].[SeedTable]  ([LastNames],[FirstNames],[streetnames],[city],[state],[gender]) values ('Brooks','Molly','','Leadville','CO','f')
insert into [dbo].[SeedTable]  ([LastNames],[FirstNames],[streetnames],[city],[state],[gender]) values ('Bennett','Madelyn','','Leadville','CO','f')
insert into [dbo].[SeedTable]  ([LastNames],[FirstNames],[streetnames],[city],[state],[gender]) values ('Gray','Scarlett','','Leadville','CO','f')
insert into [dbo].[SeedTable]  ([LastNames],[FirstNames],[streetnames],[city],[state],[gender]) values ('James','Andrea','','Leadville','CO','f')
insert into [dbo].[SeedTable]  ([LastNames],[FirstNames],[streetnames],[city],[state],[gender]) values ('Reyes','Genesis','','Leadville','CO','f')
insert into [dbo].[SeedTable]  ([LastNames],[FirstNames],[streetnames],[city],[state],[gender]) values ('Cruz','Eva','','Leadville','CO','f')
insert into [dbo].[SeedTable]  ([LastNames],[FirstNames],[streetnames],[city],[state],[gender]) values ('Hughes','Ariana','','Leadville','CO','f')
insert into [dbo].[SeedTable]  ([LastNames],[FirstNames],[streetnames],[city],[state],[gender]) values ('Price','Madeline','','Leadville','CO','f')
insert into [dbo].[SeedTable]  ([LastNames],[FirstNames],[streetnames],[city],[state],[gender]) values ('Myers','Brooke','','Leadville','CO','f')
insert into [dbo].[SeedTable]  ([LastNames],[FirstNames],[streetnames],[city],[state],[gender]) values ('Long','Caroline','','Leadville','CO','f')
insert into [dbo].[SeedTable]  ([LastNames],[FirstNames],[streetnames],[city],[state],[gender]) values ('Foster','Bailey','','Leadville','CO','f')
insert into [dbo].[SeedTable]  ([LastNames],[FirstNames],[streetnames],[city],[state],[gender]) values ('Sanders','Melanie','','Leadville','CO','f')
insert into [dbo].[SeedTable]  ([LastNames],[FirstNames],[streetnames],[city],[state],[gender]) values ('Ross','Kennedy','','Leadville','CO','f')
insert into [dbo].[SeedTable]  ([LastNames],[FirstNames],[streetnames],[city],[state],[gender]) values ('Morales','Destiny','','Leadville','CO','f')
insert into [dbo].[SeedTable]  ([LastNames],[FirstNames],[streetnames],[city],[state],[gender]) values ('Powell','Maria','','Leadville','CO','f')
insert into [dbo].[SeedTable]  ([LastNames],[FirstNames],[streetnames],[city],[state],[gender]) values ('Sullivan','Naomi','','Leadville','CO','f')
insert into [dbo].[SeedTable]  ([LastNames],[FirstNames],[streetnames],[city],[state],[gender]) values ('Russell','London','','Leadville','CO','f')
insert into [dbo].[SeedTable]  ([LastNames],[FirstNames],[streetnames],[city],[state],[gender]) values ('Ortiz','Payton','','Leadville','CO','f')
insert into [dbo].[SeedTable]  ([LastNames],[FirstNames],[streetnames],[city],[state],[gender]) values ('Jenkins','Lydia','','Leadville','CO','f')
insert into [dbo].[SeedTable]  ([LastNames],[FirstNames],[streetnames],[city],[state],[gender]) values ('Gutiérrez','Ellie','','Leadville','CO','f')
insert into [dbo].[SeedTable]  ([LastNames],[FirstNames],[streetnames],[city],[state],[gender]) values ('Perry','Mariah','','Leadville','CO','f')
insert into [dbo].[SeedTable]  ([LastNames],[FirstNames],[streetnames],[city],[state],[gender]) values ('Butler','Aubree','','Leadville','CO','f')
insert into [dbo].[SeedTable]  ([LastNames],[FirstNames],[streetnames],[city],[state],[gender]) values ('Barnes','Kaitlyn','','Leadville','CO','f')
insert into [dbo].[SeedTable]  ([LastNames],[FirstNames],[streetnames],[city],[state],[gender]) values ('Fisher','Meredith','','Leadville','CO','f')