//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class ActionStatu
{
    public ActionStatu()
    {
        this.PropertyToCleanUpStatus = new HashSet<PropertyToCleanUpStatu>();
    }

    public int ActionStatusID { get; set; }
    public string ActionStatus { get; set; }

    public virtual ICollection<PropertyToCleanUpStatu> PropertyToCleanUpStatus { get; set; }
}

public partial class BloodResult
{
    public BloodResult()
    {
        this.People = new HashSet<Person>();
    }

    public int BloodResultsID { get; set; }
    public int PersonID { get; set; }
    public System.DateTime SampleDate { get; set; }
    public Nullable<int> LeadValue { get; set; }
    public Nullable<int> LeadValueCategoryID { get; set; }
    public Nullable<int> StatusID { get; set; }
    public Nullable<int> LabID { get; set; }
    public Nullable<System.DateTime> LabDate { get; set; }
    public Nullable<int> SampleID { get; set; }

    public virtual Lab Lab { get; set; }
    public virtual LeadValueCategory LeadValueCategory { get; set; }
    public virtual Sample Sample { get; set; }
    public virtual Status Status { get; set; }
    public virtual ICollection<Person> People { get; set; }
}

public partial class Classification
{
    public Classification()
    {
        this.Notes = new HashSet<Note>();
    }

    public int ClassificationID { get; set; }
    public string Classification1 { get; set; }

    public virtual ICollection<Note> Notes { get; set; }
}

public partial class CleanUpStatu
{
    public CleanUpStatu()
    {
        this.PropertyToCleanUpStatus = new HashSet<PropertyToCleanUpStatu>();
    }

    public int CleanUpStatusID { get; set; }
    public string CleanUpStatus { get; set; }

    public virtual ICollection<PropertyToCleanUpStatu> PropertyToCleanUpStatus { get; set; }
}

public partial class ConstructionType
{
    public ConstructionType()
    {
        this.Properties = new HashSet<Property>();
    }

    public int ConstructionTypeID { get; set; }
    public string ConstructionType1 { get; set; }

    public virtual ICollection<Property> Properties { get; set; }
}

public partial class Family
{
    public Family()
    {
        this.Languages = new HashSet<Language>();
        this.Notes = new HashSet<Note>();
        this.People = new HashSet<Person>();
    }

    public int FamilyID { get; set; }
    public string FamilyLastName { get; set; }
    public Nullable<byte> NumberofSmokers { get; set; }
    public Nullable<bool> LeadDishware { get; set; }
    public Nullable<byte> InOutPets { get; set; }
    public Nullable<int> PrimaryLanguageID { get; set; }
    public Nullable<int> NotesID { get; set; }

    public virtual Language Language { get; set; }
    public virtual ICollection<Language> Languages { get; set; }
    public virtual ICollection<Note> Notes { get; set; }
    public virtual ICollection<Person> People { get; set; }
}

public partial class FPLinkType
{
    public FPLinkType()
    {
        this.PersonToProperties = new HashSet<PersonToProperty>();
    }

    public int FPLinkTypeID { get; set; }
    public string FPLinkType1 { get; set; }

    public virtual ICollection<PersonToProperty> PersonToProperties { get; set; }
}

public partial class Lab
{
    public Lab()
    {
        this.BloodResults = new HashSet<BloodResult>();
    }

    public int LabID { get; set; }
    public string labName { get; set; }
    public string HouseNumber { get; set; }
    public string Apartment { get; set; }
    public string Street { get; set; }
    public string City { get; set; }
    public string State { get; set; }
    public string Country { get; set; }
    public Nullable<System.DateTime> YearOpen { get; set; }
    public Nullable<System.DateTime> YearClosed { get; set; }
    public string Notes { get; set; }

    public virtual ICollection<BloodResult> BloodResults { get; set; }
}

public partial class Language
{
    public Language()
    {
        this.Families = new HashSet<Family>();
        this.People = new HashSet<Person>();
        this.Families1 = new HashSet<Family>();
        this.People1 = new HashSet<Person>();
    }

    public int LanguageID { get; set; }
    public string Name { get; set; }

    public virtual ICollection<Family> Families { get; set; }
    public virtual ICollection<Person> People { get; set; }
    public virtual ICollection<Family> Families1 { get; set; }
    public virtual ICollection<Person> People1 { get; set; }
}

public partial class LeadValueCategory
{
    public LeadValueCategory()
    {
        this.BloodResults = new HashSet<BloodResult>();
    }

    public int LeadValueCategoryID { get; set; }
    public string LeadValueCategory1 { get; set; }

    public virtual ICollection<BloodResult> BloodResults { get; set; }
}

public partial class Medium
{
    public Medium()
    {
        this.PropertyToCleanUpStatus = new HashSet<PropertyToCleanUpStatu>();
        this.Samples = new HashSet<Sample>();
    }

    public int MediumID { get; set; }
    public string Medium1 { get; set; }

    public virtual ICollection<PropertyToCleanUpStatu> PropertyToCleanUpStatus { get; set; }
    public virtual ICollection<Sample> Samples { get; set; }
}

public partial class Note
{
    public Note()
    {
        this.PropertyToNotes = new HashSet<PropertyToNote>();
        this.Families = new HashSet<Family>();
        this.People = new HashSet<Person>();
    }

    public int NotesID { get; set; }
    public string Note1 { get; set; }
    public int EntityID { get; set; }
    public int ClassificationID { get; set; }
    public int NoteTypeID { get; set; }

    public virtual Classification Classification { get; set; }
    public virtual NoteType NoteType { get; set; }
    public virtual ICollection<PropertyToNote> PropertyToNotes { get; set; }
    public virtual ICollection<Family> Families { get; set; }
    public virtual ICollection<Person> People { get; set; }
}

public partial class NoteType
{
    public NoteType()
    {
        this.Notes = new HashSet<Note>();
    }

    public int NoteTypeID { get; set; }
    public string NoteType1 { get; set; }

    public virtual ICollection<Note> Notes { get; set; }
}

public partial class Person
{
    public Person()
    {
        this.PersonToProperties = new HashSet<PersonToProperty>();
        this.BloodResults = new HashSet<BloodResult>();
        this.Families = new HashSet<Family>();
        this.Languages = new HashSet<Language>();
        this.Notes = new HashSet<Note>();
        this.Questoinaires = new HashSet<Questoinaire>();
    }

    public int PersonID { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public Nullable<System.DateTime> BirthDate { get; set; }
    public string Sex { get; set; }
    public Nullable<int> PrimaryLanguageID { get; set; }
    public Nullable<int> ReleaseStatusID { get; set; }
    public Nullable<int> StatusID { get; set; }

    public virtual Language Language { get; set; }
    public virtual ReleaseStatu ReleaseStatu { get; set; }
    public virtual Status Status { get; set; }
    public virtual ICollection<PersonToProperty> PersonToProperties { get; set; }
    public virtual ICollection<BloodResult> BloodResults { get; set; }
    public virtual ICollection<Family> Families { get; set; }
    public virtual ICollection<Language> Languages { get; set; }
    public virtual ICollection<Note> Notes { get; set; }
    public virtual ICollection<Questoinaire> Questoinaires { get; set; }
}

public partial class PersonToProperty
{
    public int PersonID { get; set; }
    public int PropertyID { get; set; }
    public Nullable<System.DateTime> MoveInDate { get; set; }
    public Nullable<System.DateTime> MoveOutDate { get; set; }
    public Nullable<int> FPLinkTypeID { get; set; }

    public virtual FPLinkType FPLinkType { get; set; }
    public virtual Person Person { get; set; }
    public virtual Property Property { get; set; }
}

public partial class Property
{
    public Property()
    {
        this.PersonToProperties = new HashSet<PersonToProperty>();
        this.PropertyToCleanUpStatus = new HashSet<PropertyToCleanUpStatu>();
        this.PropertyToNotes = new HashSet<PropertyToNote>();
        this.Questoinaires = new HashSet<Questoinaire>();
        this.Samples = new HashSet<Sample>();
    }

    public int PropertyID { get; set; }
    public string PropertyName { get; set; }
    public string HouseNumber { get; set; }
    public string Apartment { get; set; }
    public string Street { get; set; }
    public string City { get; set; }
    public string State { get; set; }
    public string Country { get; set; }
    public Nullable<int> YearBuilt { get; set; }
    public Nullable<int> CleanUpStatusID { get; set; }
    public Nullable<int> ConstructionTypeID { get; set; }

    public virtual ConstructionType ConstructionType { get; set; }
    public virtual ICollection<PersonToProperty> PersonToProperties { get; set; }
    public virtual Property Property1 { get; set; }
    public virtual Property Property2 { get; set; }
    public virtual ICollection<PropertyToCleanUpStatu> PropertyToCleanUpStatus { get; set; }
    public virtual ICollection<PropertyToNote> PropertyToNotes { get; set; }
    public virtual ICollection<Questoinaire> Questoinaires { get; set; }
    public virtual ICollection<Sample> Samples { get; set; }
}

public partial class PropertyToCleanUpStatu
{
    public int CleanUpStatusID { get; set; }
    public int PropertyID { get; set; }
    public System.DateTime StartDate { get; set; }
    public Nullable<System.DateTime> CompleteDate { get; set; }
    public string Clearance { get; set; }
    public string Description { get; set; }
    public Nullable<int> ActionStatusID { get; set; }
    public Nullable<System.DateTime> ActionStatusDate { get; set; }
    public Nullable<int> MediumID { get; set; }

    public virtual ActionStatu ActionStatu { get; set; }
    public virtual CleanUpStatu CleanUpStatu { get; set; }
    public virtual Medium Medium { get; set; }
    public virtual Property Property { get; set; }
}

public partial class PropertyToNote
{
    public int PropertyID { get; set; }
    public int NotesID { get; set; }
    public System.DateTime NoteDate { get; set; }

    public virtual Note Note { get; set; }
    public virtual Property Property { get; set; }
}

public partial class Questoinaire
{
    public Questoinaire()
    {
        this.People = new HashSet<Person>();
    }

    public int QuestionaireID { get; set; }
    public Nullable<System.DateTime> DateAdministered { get; set; }
    public string Source { get; set; }
    public Nullable<int> MouthingIndex { get; set; }
    public Nullable<bool> Nursing { get; set; }
    public Nullable<bool> Pacifier { get; set; }
    public Nullable<int> DayCareID { get; set; }
    public string Notes { get; set; }

    public virtual Property Property { get; set; }
    public virtual ICollection<Person> People { get; set; }
}

public partial class ReleaseStatu
{
    public ReleaseStatu()
    {
        this.People = new HashSet<Person>();
    }

    public int ReleaseStatusID { get; set; }
    public string ReleaseStatusDesc { get; set; }

    public virtual ICollection<Person> People { get; set; }
}

public partial class Sample
{
    public Sample()
    {
        this.BloodResults = new HashSet<BloodResult>();
    }

    public int SampleID { get; set; }
    public string Object { get; set; }
    public string Description { get; set; }
    public Nullable<System.DateTime> SampleDate { get; set; }
    public string Notes { get; set; }
    public Nullable<int> PropertyID { get; set; }
    public Nullable<int> SampleTypeID { get; set; }
    public Nullable<int> MediuamID { get; set; }

    public virtual ICollection<BloodResult> BloodResults { get; set; }
    public virtual Medium Medium { get; set; }
    public virtual Property Property { get; set; }
    public virtual SampleType SampleType { get; set; }
}

public partial class SampleType
{
    public SampleType()
    {
        this.Samples = new HashSet<Sample>();
    }

    public int SampleTypeID { get; set; }
    public string SampleType1 { get; set; }

    public virtual ICollection<Sample> Samples { get; set; }
}

public partial class SeedTable
{
    public int id { get; set; }
    public string LastNames { get; set; }
    public string FirstNames { get; set; }
    public string streetnames { get; set; }
    public string city { get; set; }
    public string state { get; set; }
}

public partial class Status
{
    public Status()
    {
        this.BloodResults = new HashSet<BloodResult>();
        this.People = new HashSet<Person>();
    }

    public int StatusID { get; set; }
    public string StatusName { get; set; }

    public virtual ICollection<BloodResult> BloodResults { get; set; }
    public virtual ICollection<Person> People { get; set; }
}
