<%@ Page Language="C#" MasterPageFile="~/Site.master" AutoEventWireup="true" CodeFile="AssociatePersonFamily.aspx.cs" Inherits="AssociatePersonFamily" Trace="false" EnableViewState="true"%>

<asp:Content ID="headContent" ContentPlaceHolderID="head" Runat="Server"></asp:Content>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">


    <div class="DD">

        <h2 class="DDSubHeader">Associate Person to Family</h2>


    <table>
    <tr>
    <td>List People with Existing Family Associations? </td>

    <td>
    <asp:RadioButtonList ID="rblWithoutFamily" runat="server" RepeatDirection="Horizontal" ToolTip="List Clients With Family Associaionts" OnSelectedIndexChanged="rblWithoutFamily_Changed" AutoPostBack=true>
                    <asp:ListItem Value="1" Selected="True">No</asp:ListItem>
                    <asp:ListItem Value="0">Yes</asp:ListItem>
                </asp:RadioButtonList>
                </td>
    </tr>
    
        <tr><td colspan="2"><hr /></td></tr>
    
        <tr><td style="text-align:right">Person: </td>
    <td>
        <asp:DropDownList ID="ddlPeople" runat="server" OnSelectedIndexChanged="ddlPeopleChanged" AutoPostBack=true></asp:DropDownList></td>
    </tr>


    <tr><td style="text-align:right">Family: </td>
    <td>
        <asp:DropDownList ID="ddlFamily" runat="server" OnSelectedIndexChanged="ddlFamilyChanged"></asp:DropDownList></td>
    </tr>
    
        <tr><td colspan="2"><hr /></td></tr>
    
        <tr><td colspan="2" style="text-align:right"><asp:Button ID="bAssociateFamilies" runat="server" Text="Associate >>" onClick="bAssociateFamilies_Click" /> </td></tr>

    </table>


    <asp:GridView ID="GridView1" AllowSorting="true" AllowPaging="true" Runat="server"
        DataSourceID="SqlDataSource_PersontoFamilies" AutoGenerateEditButton="false" DataKeyNames="PersonID,FamilyID"
        AutoGenerateColumns="false" AutoGenerateDeleteButton="FALSE" AutoGenerateSelectButton="False" CssClass="DD">

        <Columns>
            <asp:BoundField ReadOnly="true" HeaderText="PersonID" DataField="PersonID" SortExpression="PersonID" />

            <asp:BoundField ReadOnly="true" HeaderText="LastName" DataField="LastName" SortExpression="LastName" />

            <asp:BoundField ReadOnly="true" HeaderText="FirstName" DataField="FirstName" SortExpression="FirstName" />

            <asp:BoundField HeaderText="BirthDate" DataField="BirthDate" SortExpression="BirthDate" DataFormatString="{0:MM/dd/yyyy}" ReadOnly="True" />

            <asp:BoundField HeaderText="FamilyID" DataField="FamilyID" SortExpression="FamilyID" />
            
            <asp:BoundField HeaderText="FamilyName" DataField="FamilyName" SortExpression="FamilyName" />

            <asp:BoundField HeaderText="AddressLine1" DataField="AddressLine1" SortExpression="AddressLine1" />

            <asp:BoundField HeaderText="AddressLine2" DataField="AddressLine2" SortExpression="AddressLine2" />

        </Columns>
      </asp:GridView>

            <asp:SqlDataSource ID="SqlDataSource_PersontoFamilies" Runat="server" SelectCommandType="StoredProcedure" SelectCommand="usp_SlListPersonandFamilies"
                DeleteCommandType="StoredProcedure" DeleteCommand="usp_delPersonfromFamily" 
                ConnectionString="<%$ ConnectionStrings:csLCCHP %>" 
          >

          <SelectParameters>
              <asp:Parameter Type="String" Name="PersonID"></asp:Parameter>
          </SelectParameters>
            
          <DeleteParameters>
                <asp:parameter Type=Int32 Name="PersonID" />
                <asp:Parameter Type=Int32 Name="FamilyID" />
          </DeleteParameters>  

      </asp:SqlDataSource>
      <asp:Label runat="server" ID="gridText"></asp:Label>

    </div>
   
    <p class="DD"><asp:label ID="lbOutput" runat="server"></asp:label></p>
    
</asp:Content>
