
<%@ Page Language="C#" MasterPageFile="~/Site.master" AutoEventWireup="true"  CodeFile="AutoCompleteTest.aspx.cs" Inherits="autoCompleteTest" Trace="true" EnableViewState="true" %>

<asp:Content ID="headContent" ContentPlaceHolderID="head" Runat="Server"></asp:Content>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">



<%@ Register Assembly="AjaxControlToolkit" Namespace="AjaxControlToolkit" TagPrefix="cc1" %>

    <div class="DD">

    <h2 class="DDSubHeader">Find Client(s) in Lead Research Study</h2>


    <table>
    <tr>
    <td> <p>
    FirstName:
    <asp:TextBox ID="tbFirstName" runat="server"></asp:TextBox></p>
    </td>
    <td>
        <asp:Button ID="SearchByTagButton" runat="server" Text="SEARCH"
            onclick="SearchByTagButton_Click" /><br />
        
    </td>
    <tr>
    <td> LastName:
        <asp:TextBox ID="tbLastName" runat="server"></asp:TextBox>
    </td>
    <td> Date of Birth:
        <asp:TextBox ID="tbBirthDate" runat="server"></asp:TextBox>
    </td>
    </tr>
    

    </table>
    
        <p>&nbsp;</p>

    <asp:GridView ID="gvClients" runat="server" AllowSorting="true" AllowPaging="true"
        AutoGenerateEditButton="false" DataKeyNames="PersonId"
        AutoGenerateColumns="false" AutoGenerateDeleteButton="false" AutoGenerateSelectButton="False" CssClass="DD">
        <Columns>
            <asp:BoundField ReadOnly="true" HeaderText="ID" DataField="PersonID" SortExpression="PersonID" />
            <asp:BoundField ReadOnly="true" HeaderText="First Name" DataField="FirstName" SortExpression="FirstName" />
            <asp:BoundField ReadOnly="true" HeaderText="Last Name" DataField="LastName" SortExpression="LastName" />
            <asp:BoundField ReadOnly="true" HeaderText="Birth Date" DataField="BirthDate" SortExpression="BirthDate" />

        <asp:hyperlinkfield datatextfield="PersonId"
        datanavigateurlfields="PersonId" HeaderText="Edit"
        datanavigateurlformatstring="EditClientInfo.aspx?pid={0}"  />
    </Columns>

    </asp:GridView>
    
        <p>&nbsp;</p>

 
</div>

    </asp:Content>