<%@ Page Language="C#" AutoEventWireup="true" CodeFile="EditBloodLeadResults.aspx.cs" Inherits="EditBloodLeadResults" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
    <div>
    

        <asp:GridView ID="GridView1" AllowSorting="true" AllowPaging="true" Runat="server"
        DataSourceID="SqlDataSource1" AutoGenerateEditButton="true" DataKeyNames="BloodTestResultsID"
        AutoGenerateColumns="True" AutoGenerateDeleteButton="True" AutoGenerateSelectButton="False">

        <Columns>
          <asp:BoundField ReadOnly="true" HeaderText="ID" DataField="BloodTestResultsID" SortExpression="au_id" />
          <asp:BoundField Readonly="true" HeaderText="PersonID" DataField="PersonID" SortExpression="PersonID" />
            
          <asp:BoundField HeaderText="SampleDate" DataField="SampleDate" SortExpression="SampleDate" />

            <asp:BoundField HeaderText="LeadValue" DataField="LeadValue" SortExpression="LeadValue" />
        </Columns>
      </asp:GridView>

      <asp:SqlDataSource ID="SqlDataSource1" Runat="server" SelectCommand="SELECT [BloodTestResultsID]
      ,[isBaseline]
      ,[PersonID]
      ,[SampleDate]
      ,[LabSubmissionDate]
      ,[LeadValue]
      ,[LeadValueCategoryID]
      ,[HemoglobinValue]
      ,[HemoglobinValueCategoryID]
      ,[HematocritValueCategoryID]
      ,[LabID]
      ,[BloodTestCosts]
      ,[SampleTypeID]
      ,[TakenAfterPropertyRemediationCompleted]
      ,[ModifiedDate]
      ,[CreatedDate]
      ,[HematocritValue]
      ,[ExcludeResult]
      ,[HistoricBloodTestResultsID]
      ,[HistoricLabResultsID]
  FROM [LCCHPDev].[dbo].[BloodTestResults]"
        
          UpdateCommand="UPDATE [BloodTestResults] SET [LeadValue] = @LeadValue, [SampleDate] = @SampleDate WHERE [PersonID] = @PersonID"

          DeleteCommand="delete from BloodTestResults where [BloodTestResultsID] = @BloodTestResultsID"

          InsertCommand="Insert into BloodTestResults (LeadValue, SampleDate) Values (@LeadValue, @SampleDate)"

        ConnectionString="<%$ ConnectionStrings:csLCCHP %>" />



    </div>
    </form>
</body>
</html>
