sp_rename 'HomeRemedies','HomeRemedy'
alter table property alter column [State] char(2)
alter table phoneNumber alter column phonenumber bigint
alter table Family alter column [PrimaryLanguageID] tinyint null
alter table accessagreement alter column notes varchar(3000)
alter table accessPurpose alter column accessPurposeDescription varchar(253)
alter table accessPurpose alter column accessPurposeName varchar(50)
alter table Area alter column AreaDescription varchar(253)
alter table remediation alter column notes varchar(3000)
alter table lab alter column historicLabID varchar(512)
alter table CleanUpStatus alter column CleanUpStatusName varchar(50)
alter table ConstructionType alter column ConstructionTypeDescription varchar(253)
alter table Contractor alter column ContractorDescription varchar(253)
alter table DayCare alter column DaycareDescription varchar(253)
alter table Ethnicity alter column EthnicityCode char(3)
alter table ForeignFood alter column ForeignFoodDescription varchar(253)
alter table Hobby alter column HobbyDescription varchar(253)
alter table HouseholdSourcesofLead alter column HouseholdItemDescription varchar(253)
alter table HomeRemedy alter column homeRemedyDescription varchar(253)
alter table Lab alter column LabDescription varchar(253)
alter table Medium alter column MediumDescription varchar(253)
alter table Occupation alter column OccupationDescription varchar(253)
alter table Occupation alter column OccupationNotes varchar(3000)
alter table SampleLevelCategory alter column SampleLevelCategoryDescription varchar(253)
alter table SampleLevelCategory alter column SampleLevelCategoryName varchar(50)
alter table sampleType alter column SampleTypeDescription varchar(253)
alter table [status] alter column StatusDescription varchar(253)
alter table Units alter column UnitsDescription varchar(253)

